### ISSUE TITLE
Lutometry Error

### ISSUE THREAD

**Issue by LazaroFilm** [soten355/Lutometry#1]
After downloading, launching and accepting the "Open Anyway" message, I get this error: https://imgur.com/a/6iyVPt5

**Comment by soten355** [comment]
Tested and can confirm the same issue. It's because of how the app was built via Py2app. Currently building a new binary.

**Comment by soten355** [comment]
It seems that building an app for Mac's via Py2App creates an app that is expecting the end user to have Python 3.9.0 installed. I'm currently looking into making the app work regardless of which Python is or isn't installed.

**Comment by soten355** [comment]
Got it to work. Wasn't an issue with Py2App, but NumPy.

For those building from source:

When you install NumPy, you need to install it from a binary. Use this command line:

`pip install --only-binary :all: numpy`
